from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1200, 1000)  # 设置固定窗口大小
        MainWindow.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.MSWindowsFixedSizeDialogHint)  # 禁用调整窗口大小

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setStyleSheet(
            "font: bold 18px; color: white; background-color: rgba(255, 255, 255, 150); padding: 5px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.menuButtonLayout = QtWidgets.QHBoxLayout()
        self.menuButtonLayout.setObjectName("menuButtonLayout")
        self.mainPageButton = QtWidgets.QPushButton(self.centralwidget)
        self.mainPageButton.setObjectName("mainPageButton")
        self.mainPageButton.setStyleSheet("color: black;")
        self.menuButtonLayout.addWidget(self.mainPageButton)
        self.abnormalBehaviorButton = QtWidgets.QPushButton(self.centralwidget)
        self.abnormalBehaviorButton.setObjectName("abnormalBehaviorButton")
        self.abnormalBehaviorButton.setStyleSheet("color: black;")
        self.menuButtonLayout.addWidget(self.abnormalBehaviorButton)
        self.peopleFlowMonitorButton = QtWidgets.QPushButton(self.centralwidget)
        self.peopleFlowMonitorButton.setObjectName("peopleFlowMonitorButton")
        self.peopleFlowMonitorButton.setStyleSheet("color: black;")
        self.menuButtonLayout.addWidget(self.peopleFlowMonitorButton)
        self.modifyInfoButton = QtWidgets.QPushButton(self.centralwidget)
        self.modifyInfoButton.setObjectName("modifyInfoButton")
        self.modifyInfoButton.setStyleSheet("color: black;")
        self.menuButtonLayout.addWidget(self.modifyInfoButton)
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setObjectName("logoutButton")
        self.logoutButton.setStyleSheet("color: black;")
        self.menuButtonLayout.addWidget(self.logoutButton)
        self.verticalLayout.addLayout(self.menuButtonLayout)

        # 添加复选框
        self.abnormalBehaviorToggle = QtWidgets.QCheckBox(self.centralwidget)
        self.abnormalBehaviorToggle.setObjectName("abnormalBehaviorToggle")
        self.abnormalBehaviorToggle.setStyleSheet("color: white;")
        self.verticalLayout.addWidget(self.abnormalBehaviorToggle)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.camera1GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.camera1GroupBox.setObjectName("camera1GroupBox")
        self.camera1GroupBox.setStyleSheet("color: white;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.camera1GroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.camera1View1 = QLabel(self.camera1GroupBox)
        self.camera1View1.setObjectName("camera1View1")
        self.verticalLayout_2.addWidget(self.camera1View1)
        self.camera1View2 = QLabel(self.camera1GroupBox)
        self.camera1View2.setObjectName("camera1View2")
        self.verticalLayout_2.addWidget(self.camera1View2)
        self.camera1View3 = QLabel(self.camera1GroupBox)
        self.camera1View3.setObjectName("camera1View3")
        self.verticalLayout_2.addWidget(self.camera1View3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton1_1 = QtWidgets.QRadioButton(self.camera1GroupBox)
        self.radioButton1_1.setObjectName("radioButton1_1")
        self.radioButton1_1.setStyleSheet("color: white;")
        self.horizontalLayout_2.addWidget(self.radioButton1_1)
        self.radioButton1_2 = QtWidgets.QRadioButton(self.camera1GroupBox)
        self.radioButton1_2.setObjectName("radioButton1_2")
        self.radioButton1_2.setStyleSheet("color: white;")
        self.horizontalLayout_2.addWidget(self.radioButton1_2)
        self.radioButton1_3 = QtWidgets.QRadioButton(self.camera1GroupBox)
        self.radioButton1_3.setObjectName("radioButton1_3")
        self.radioButton1_3.setStyleSheet("color: white;")
        self.horizontalLayout_2.addWidget(self.radioButton1_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.camera1GroupBox)
        self.camera2GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.camera2GroupBox.setObjectName("camera2GroupBox")
        self.camera2GroupBox.setStyleSheet("color: white;")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.camera2GroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.camera2View1 = QLabel(self.camera2GroupBox)
        self.camera2View1.setObjectName("camera2View1")
        self.verticalLayout_6.addWidget(self.camera2View1)
        self.camera2View2 = QLabel(self.camera2GroupBox)
        self.camera2View2.setObjectName("camera2View2")
        self.verticalLayout_6.addWidget(self.camera2View2)
        self.camera2View3 = QLabel(self.camera2GroupBox)
        self.camera2View3.setObjectName("camera2View3")
        self.verticalLayout_6.addWidget(self.camera2View3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton2_1 = QtWidgets.QRadioButton(self.camera2GroupBox)
        self.radioButton2_1.setObjectName("radioButton2_1")
        self.radioButton2_1.setStyleSheet("color: white;")
        self.horizontalLayout_3.addWidget(self.radioButton2_1)
        self.radioButton2_2 = QtWidgets.QRadioButton(self.camera2GroupBox)
        self.radioButton2_2.setObjectName("radioButton2_2")
        self.radioButton2_2.setStyleSheet("color: white;")
        self.horizontalLayout_3.addWidget(self.radioButton2_2)
        self.radioButton2_3 = QtWidgets.QRadioButton(self.camera2GroupBox)
        self.radioButton2_3.setObjectName("radioButton2_3")
        self.radioButton2_3.setStyleSheet("color: white;")
        self.horizontalLayout_3.addWidget(self.radioButton2_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.camera2GroupBox)
        self.camera3GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.camera3GroupBox.setObjectName("camera3GroupBox")
        self.camera3GroupBox.setStyleSheet("color: white;")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.camera3GroupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.camera3View1 = QLabel(self.camera3GroupBox)
        self.camera3View1.setObjectName("camera3View1")
        self.verticalLayout_10.addWidget(self.camera3View1)
        self.camera3View2 = QLabel(self.camera3GroupBox)
        self.camera3View2.setObjectName("camera3View2")
        self.verticalLayout_10.addWidget(self.camera3View2)
        self.camera3View3 = QLabel(self.camera3GroupBox)
        self.camera3View3.setObjectName("camera3View3")
        self.verticalLayout_10.addWidget(self.camera3View3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton3_1 = QtWidgets.QRadioButton(self.camera3GroupBox)
        self.radioButton3_1.setObjectName("radioButton3_1")
        self.radioButton3_1.setStyleSheet("color: white;")
        self.horizontalLayout_4.addWidget(self.radioButton3_1)
        self.radioButton3_2 = QtWidgets.QRadioButton(self.camera3GroupBox)
        self.radioButton3_2.setObjectName("radioButton3_2")
        self.radioButton3_2.setStyleSheet("color: white;")
        self.horizontalLayout_4.addWidget(self.radioButton3_2)
        self.radioButton3_3 = QtWidgets.QRadioButton(self.camera3GroupBox)
        self.radioButton3_3.setObjectName("radioButton3_3")
        self.radioButton3_3.setStyleSheet("color: white;")
        self.horizontalLayout_4.addWidget(self.radioButton3_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addWidget(self.camera3GroupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.alertList = QtWidgets.QGroupBox(self.centralwidget)
        self.alertList.setStyleSheet("color: white; background-color: rgba(255, 255, 255, 150); padding: 5px;")
        self.alertList.setObjectName("alertList")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.alertList)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.alertTextEdit = QtWidgets.QTextEdit(self.alertList)  # 添加 QTextEdit
        self.alertTextEdit.setObjectName("alertTextEdit")
        self.alertTextEdit.setReadOnly(True)  # 设置为只读
        self.verticalLayout_14.addWidget(self.alertTextEdit)
        self.verticalLayout.addWidget(self.alertList)

        self.historyRecord = QtWidgets.QGroupBox(self.centralwidget)
        self.historyRecord.setStyleSheet("color: white; background-color: rgba(255, 255, 255, 150); padding: 5px;")
        self.historyRecord.setObjectName("historyRecord")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.historyRecord)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.historyTextEdit = QtWidgets.QTextEdit(self.historyRecord)  # 添加 QTextEdit
        self.historyTextEdit.setObjectName("historyTextEdit")
        self.historyTextEdit.setReadOnly(True)  # 设置为只读
        self.verticalLayout_15.addWidget(self.historyTextEdit)
        self.verticalLayout.addWidget(self.historyRecord)

        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setStyleSheet(
            "font: bold 14px; color: white; background-color: #4CAF50; border: none; padding: 10px 24px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 16px;")
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout.addWidget(self.exportButton)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.peopleFlowMonitorButton.clicked.connect(MainWindow.open_people_flow_monitor)  # type: ignore
        self.modifyInfoButton.clicked.connect(MainWindow.open_password_change_dialog)  # type: ignore
        self.logoutButton.clicked.connect(MainWindow.open_login_dialog)  # type: ignore
        self.mainPageButton.clicked.connect(MainWindow.open_face_registration)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "异常行为监控"))
        self.mainPageButton.setText(_translate("MainWindow", "人脸录入"))
        self.abnormalBehaviorButton.setText(_translate("MainWindow", "异常行为监控"))
        self.peopleFlowMonitorButton.setText(_translate("MainWindow", "人流量监控"))
        self.modifyInfoButton.setText(_translate("MainWindow", "修改密码"))
        self.logoutButton.setText(_translate("MainWindow", "退出账号"))
        self.camera1GroupBox.setTitle(_translate("MainWindow", "摄像头 1"))
        self.radioButton1_1.setText(_translate("MainWindow", "源 1"))
        self.radioButton1_2.setText(_translate("MainWindow", "源 2"))
        self.radioButton1_3.setText(_translate("MainWindow", "源 3"))
        self.camera2GroupBox.setTitle(_translate("MainWindow", "摄像头 2"))
        self.radioButton2_1.setText(_translate("MainWindow", "源 1"))
        self.radioButton2_2.setText(_translate("MainWindow", "源 2"))
        self.radioButton2_3.setText(_translate("MainWindow", "源 3"))
        self.camera3GroupBox.setTitle(_translate("MainWindow", "摄像头 3"))
        self.radioButton3_1.setText(_translate("MainWindow", "源 1"))
        self.radioButton3_2.setText(_translate("MainWindow", "源 2"))
        self.radioButton3_3.setText(_translate("MainWindow", "源 3"))
        self.alertList.setTitle(_translate("MainWindow", "异常行为警报列表"))
        self.historyRecord.setTitle(_translate("MainWindow", "异常行为历史记录"))
        self.exportButton.setText(_translate("MainWindow", "导出数据"))
        self.abnormalBehaviorToggle.setText(_translate("MainWindow", "启用异常行为检测"))
