# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceLoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FaceLoginWindow(object):
    def setupUi(self, FaceLoginWindow):
        FaceLoginWindow.setObjectName("FaceLoginWindow")
        FaceLoginWindow.resize(1200, 1000)
        self.centralwidget = QtWidgets.QWidget(FaceLoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        # 创建水平布局以确保 cameraLabel 居中
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.cameraLabel = QtWidgets.QLabel(self.centralwidget)
        self.cameraLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraLabel.setStyleSheet("background-color: #c0c0c0; border: 5px solid #000;")  # 调整边框大小为5px
        self.cameraLabel.setMinimumSize(QtCore.QSize(600, 400))  # 设置最小尺寸
        self.cameraLabel.setMaximumSize(QtCore.QSize(600, 400))  # 设置最大尺寸
        self.cameraLabel.setObjectName("cameraLabel")

        # 将 cameraLabel 添加到水平布局中并居中
        self.horizontalLayout.addStretch()
        self.horizontalLayout.addWidget(self.cameraLabel)
        self.horizontalLayout.addStretch()

        self.faceLoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.faceLoginButton.setStyleSheet(
            "font: bold 14px; color: white; background-color: #4CAF50; border: none; padding: 10px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 16px;")
        self.faceLoginButton.setObjectName("faceLoginButton")
        self.verticalLayout.addWidget(self.faceLoginButton)

        FaceLoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FaceLoginWindow)
        self.menubar.setObjectName("menubar")
        FaceLoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FaceLoginWindow)
        self.statusbar.setObjectName("statusbar")
        FaceLoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FaceLoginWindow)
        QtCore.QMetaObject.connectSlotsByName(FaceLoginWindow)

    def retranslateUi(self, FaceLoginWindow):
        _translate = QtCore.QCoreApplication.translate
        FaceLoginWindow.setWindowTitle(_translate("FaceLoginWindow", "刷脸登录"))
        self.cameraLabel.setText(_translate("FaceLoginWindow", "摄像头画面"))
        self.faceLoginButton.setText(_translate("FaceLoginWindow", "刷脸登录"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    FaceLoginWindow = QtWidgets.QMainWindow()
    ui = Ui_FaceLoginWindow()
    ui.setupUi(FaceLoginWindow)
    FaceLoginWindow.show()
    sys.exit(app.exec_())
