# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PassWordChangePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordChangeDialog(object):
    def setupUi(self, PasswordChangeDialog):
        PasswordChangeDialog.setObjectName("PasswordChangeDialog")
        PasswordChangeDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(PasswordChangeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelOldPassword = QtWidgets.QLabel(PasswordChangeDialog)
        self.labelOldPassword.setObjectName("labelOldPassword")
        self.verticalLayout.addWidget(self.labelOldPassword)
        self.lineEditOldPassword = QtWidgets.QLineEdit(PasswordChangeDialog)
        self.lineEditOldPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditOldPassword.setObjectName("lineEditOldPassword")
        self.verticalLayout.addWidget(self.lineEditOldPassword)
        self.labelNewPassword = QtWidgets.QLabel(PasswordChangeDialog)
        self.labelNewPassword.setObjectName("labelNewPassword")
        self.verticalLayout.addWidget(self.labelNewPassword)
        self.lineEditNewPassword = QtWidgets.QLineEdit(PasswordChangeDialog)
        self.lineEditNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditNewPassword.setObjectName("lineEditNewPassword")
        self.verticalLayout.addWidget(self.lineEditNewPassword)
        self.labelConfirmNewPassword = QtWidgets.QLabel(PasswordChangeDialog)
        self.labelConfirmNewPassword.setObjectName("labelConfirmNewPassword")
        self.verticalLayout.addWidget(self.labelConfirmNewPassword)
        self.lineEditConfirmNewPassword = QtWidgets.QLineEdit(PasswordChangeDialog)
        self.lineEditConfirmNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditConfirmNewPassword.setObjectName("lineEditConfirmNewPassword")
        self.verticalLayout.addWidget(self.lineEditConfirmNewPassword)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonConfirm = QtWidgets.QPushButton(PasswordChangeDialog)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.horizontalLayout.addWidget(self.pushButtonConfirm)
        self.pushButtonCancel = QtWidgets.QPushButton(PasswordChangeDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PasswordChangeDialog)
        QtCore.QMetaObject.connectSlotsByName(PasswordChangeDialog)

    def retranslateUi(self, PasswordChangeDialog):
        _translate = QtCore.QCoreApplication.translate
        PasswordChangeDialog.setWindowTitle(_translate("PasswordChangeDialog", "修改密码"))
        self.labelOldPassword.setText(_translate("PasswordChangeDialog", "旧密码:"))
        self.labelNewPassword.setText(_translate("PasswordChangeDialog", "新密码:"))
        self.labelConfirmNewPassword.setText(_translate("PasswordChangeDialog", "确认新密码:"))
        self.pushButtonConfirm.setText(_translate("PasswordChangeDialog", "确认"))
        self.pushButtonCancel.setText(_translate("PasswordChangeDialog", "取消"))
