from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel

class Ui_FlowMonitoringWindow(object):
    def setupUi(self, FlowMonitoringWindow):
        FlowMonitoringWindow.setObjectName("FlowMonitoringWindow")
        FlowMonitoringWindow.resize(1200, 1000)  # 调整主窗口大小

        self.centralwidget = QtWidgets.QWidget(FlowMonitoringWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menuButtonLayout = QtWidgets.QHBoxLayout()
        self.menuButtonLayout.setObjectName("menuButtonLayout")
        self.faceRegistrationButton = QtWidgets.QPushButton(self.centralwidget)
        self.faceRegistrationButton.setObjectName("faceRegistrationButton")
        self.faceRegistrationButton.setStyleSheet("color: black;")
        self.menuButtonLayout.addWidget(self.faceRegistrationButton)
        self.abnormalBehaviorButton = QtWidgets.QPushButton(self.centralwidget)
        self.abnormalBehaviorButton.setObjectName("abnormalBehaviorButton")
        self.abnormalBehaviorButton.setStyleSheet("color: black;")
        self.menuButtonLayout.addWidget(self.abnormalBehaviorButton)
        self.peopleFlowMonitorButton = QtWidgets.QPushButton(self.centralwidget)
        self.peopleFlowMonitorButton.setObjectName("peopleFlowMonitorButton")
        self.peopleFlowMonitorButton.setStyleSheet("color: black;")
        self.menuButtonLayout.addWidget(self.peopleFlowMonitorButton)
        self.changePasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.changePasswordButton.setObjectName("changePasswordButton")
        self.changePasswordButton.setStyleSheet("color: black;")
        self.menuButtonLayout.addWidget(self.changePasswordButton)
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setObjectName("logoutButton")
        self.logoutButton.setStyleSheet("color: black;")
        self.menuButtonLayout.addWidget(self.logoutButton)
        self.verticalLayout.addLayout(self.menuButtonLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: bold 18px; color: white; background-color: rgba(255, 255, 255, 150); padding: 5px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        # 添加复选框
        self.peopleFlowToggle = QtWidgets.QCheckBox(self.centralwidget)
        self.peopleFlowToggle.setObjectName("peopleFlowToggle")
        self.peopleFlowToggle.setStyleSheet("color: white;")
        self.verticalLayout.addWidget(self.peopleFlowToggle)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.camera1GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.camera1GroupBox.setObjectName("camera1GroupBox")
        self.camera1GroupBox.setStyleSheet("color: white;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.camera1GroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget1 = QtWidgets.QStackedWidget(self.camera1GroupBox)
        self.stackedWidget1.setObjectName("stackedWidget1")
        self.camera1View1 = QLabel(self.stackedWidget1)  # 使用QLabel来显示视频
        self.camera1View1.setObjectName("camera1View1")
        self.camera1View1.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.camera1View1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget1.addWidget(self.camera1View1)
        self.camera1View2 = QtWidgets.QWidget()
        self.camera1View2.setObjectName("camera1View2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.camera1View2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget1.addWidget(self.camera1View2)
        self.camera1View3 = QtWidgets.QWidget()
        self.camera1View3.setObjectName("camera1View3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.camera1View3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget1.addWidget(self.camera1View3)
        self.verticalLayout_2.addWidget(self.stackedWidget1)
        self.label_people_flow_1 = QtWidgets.QLabel(self.camera1GroupBox)
        self.label_people_flow_1.setObjectName("label_people_flow_1")
        self.label_people_flow_1.setStyleSheet("color: white;")
        self.verticalLayout_2.addWidget(self.label_people_flow_1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton1_1 = QtWidgets.QRadioButton(self.camera1GroupBox)
        self.radioButton1_1.setObjectName("radioButton1_1")
        self.radioButton1_1.setStyleSheet("color: white;")
        self.horizontalLayout_2.addWidget(self.radioButton1_1)
        self.radioButton1_2 = QtWidgets.QRadioButton(self.camera1GroupBox)
        self.radioButton1_2.setObjectName("radioButton1_2")
        self.radioButton1_2.setStyleSheet("color: white;")
        self.horizontalLayout_2.addWidget(self.radioButton1_2)
        self.radioButton1_3 = QtWidgets.QRadioButton(self.camera1GroupBox)
        self.radioButton1_3.setObjectName("radioButton1_3")
        self.radioButton1_3.setStyleSheet("color: white;")
        self.horizontalLayout_2.addWidget(self.radioButton1_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.camera1GroupBox)
        self.camera2GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.camera2GroupBox.setObjectName("camera2GroupBox")
        self.camera2GroupBox.setStyleSheet("color: white;")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.camera2GroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget2 = QtWidgets.QStackedWidget(self.camera2GroupBox)
        self.stackedWidget2.setObjectName("stackedWidget2")
        self.camera2View1 = QLabel(self.stackedWidget2)  # 使用QLabel来显示视频
        self.camera2View1.setObjectName("camera2View1")
        self.camera2View1.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.camera2View1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget2.addWidget(self.camera2View1)
        self.camera2View2 = QtWidgets.QWidget()
        self.camera2View2.setObjectName("camera2View2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.camera2View2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget2.addWidget(self.camera2View2)
        self.camera2View3 = QtWidgets.QWidget()
        self.camera2View3.setObjectName("camera2View3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.camera2View3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidget2.addWidget(self.camera2View3)
        self.verticalLayout_6.addWidget(self.stackedWidget2)
        self.label_people_flow_2 = QtWidgets.QLabel(self.camera2GroupBox)
        self.label_people_flow_2.setObjectName("label_people_flow_2")
        self.label_people_flow_2.setStyleSheet("color: white;")
        self.verticalLayout_6.addWidget(self.label_people_flow_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton2_1 = QtWidgets.QRadioButton(self.camera2GroupBox)
        self.radioButton2_1.setObjectName("radioButton2_1")
        self.radioButton2_1.setStyleSheet("color: white;")
        self.horizontalLayout_3.addWidget(self.radioButton2_1)
        self.radioButton2_2 = QtWidgets.QRadioButton(self.camera2GroupBox)
        self.radioButton2_2.setObjectName("radioButton2_2")
        self.radioButton2_2.setStyleSheet("color: white;")
        self.horizontalLayout_3.addWidget(self.radioButton2_2)
        self.radioButton2_3 = QtWidgets.QRadioButton(self.camera2GroupBox)
        self.radioButton2_3.setObjectName("radioButton2_3")
        self.radioButton2_3.setStyleSheet("color: white;")
        self.horizontalLayout_3.addWidget(self.radioButton2_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.camera2GroupBox)
        self.camera3GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.camera3GroupBox.setObjectName("camera3GroupBox")
        self.camera3GroupBox.setStyleSheet("color: white;")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.camera3GroupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.stackedWidget3 = QtWidgets.QStackedWidget(self.camera3GroupBox)
        self.stackedWidget3.setObjectName("stackedWidget3")
        self.camera3View1 = QLabel(self.stackedWidget3)  # 使用QLabel来显示视频
        self.camera3View1.setObjectName("camera3View1")
        self.camera3View1.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.camera3View1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.stackedWidget3.addWidget(self.camera3View1)
        self.camera3View2 = QtWidgets.QWidget()
        self.camera3View2.setObjectName("camera3View2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.camera3View2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.stackedWidget3.addWidget(self.camera3View2)
        self.camera3View3 = QtWidgets.QWidget()
        self.camera3View3.setObjectName("camera3View3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.camera3View3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.stackedWidget3.addWidget(self.camera3View3)
        self.verticalLayout_10.addWidget(self.stackedWidget3)
        self.label_people_flow_3 = QtWidgets.QLabel(self.camera3GroupBox)
        self.label_people_flow_3.setObjectName("label_people_flow_3")
        self.label_people_flow_3.setStyleSheet("color: white;")
        self.verticalLayout_10.addWidget(self.label_people_flow_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton3_1 = QtWidgets.QRadioButton(self.camera3GroupBox)
        self.radioButton3_1.setObjectName("radioButton3_1")
        self.radioButton3_1.setStyleSheet("color: white;")
        self.horizontalLayout_4.addWidget(self.radioButton3_1)
        self.radioButton3_2 = QtWidgets.QRadioButton(self.camera3GroupBox)
        self.radioButton3_2.setObjectName("radioButton3_2")
        self.radioButton3_2.setStyleSheet("color: white;")
        self.horizontalLayout_4.addWidget(self.radioButton3_2)
        self.radioButton3_3 = QtWidgets.QRadioButton(self.camera3GroupBox)
        self.radioButton3_3.setObjectName("radioButton3_3")
        self.radioButton3_3.setStyleSheet("color: white;")
        self.horizontalLayout_4.addWidget(self.radioButton3_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addWidget(self.camera3GroupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.flowData = QtWidgets.QGroupBox(self.centralwidget)
        self.flowData.setStyleSheet("color: white; background-color: rgba(255, 255, 255, 150); padding: 5px;")
        self.flowData.setObjectName("flowData")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.flowData)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout.addWidget(self.flowData)
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setStyleSheet(
            "font: bold 14px; color: white; background-color: #4CAF50; border: none; padding: 10px 24px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 16px;")
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout.addWidget(self.exportButton)
        FlowMonitoringWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FlowMonitoringWindow)
        self.statusbar.setObjectName("statusbar")
        FlowMonitoringWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FlowMonitoringWindow)
        self.faceRegistrationButton.clicked.connect(FlowMonitoringWindow.open_face_registration)  # type: ignore
        self.changePasswordButton.clicked.connect(FlowMonitoringWindow.open_password_change)  # type: ignore
        self.logoutButton.clicked.connect(FlowMonitoringWindow.open_login_dialog)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FlowMonitoringWindow)

    def retranslateUi(self, FlowMonitoringWindow):
        _translate = QtCore.QCoreApplication.translate
        FlowMonitoringWindow.setWindowTitle(_translate("FlowMonitoringWindow", "Flow Monitoring"))
        self.centralwidget.setStyleSheet(_translate("FlowMonitoringWindow", "\n"
                                                                            "     QWidget#centralwidget {\n"
                                                                            "       background-image: url('D:/User/23907/Desktop/shu_qi_shi_xun/hw2/data/Background_mainPage_resized.jpg');\n"
                                                                            "       background-repeat: no-repeat;\n"
                                                                            "       background-position: center;\n"
                                                                            "       background-size: cover;\n"
                                                                            "     }\n"
                                                                            "    "))
        self.faceRegistrationButton.setText(_translate("FlowMonitoringWindow", "人脸录入"))
        self.abnormalBehaviorButton.setText(_translate("FlowMonitoringWindow", "异常行为监控"))
        self.peopleFlowMonitorButton.setText(_translate("FlowMonitoringWindow", "人流量监控"))
        self.changePasswordButton.setText(_translate("FlowMonitoringWindow", "修改密码"))
        self.logoutButton.setText(_translate("FlowMonitoringWindow", "退出账号"))
        self.label.setText(_translate("FlowMonitoringWindow", "人流量监控"))
        self.camera1GroupBox.setTitle(_translate("FlowMonitoringWindow", "摄像头 1"))
        self.radioButton1_1.setText(_translate("FlowMonitoringWindow", "源 1"))
        self.radioButton1_2.setText(_translate("FlowMonitoringWindow", "源 2"))
        self.radioButton1_3.setText(_translate("FlowMonitoringWindow", "源 3"))
        self.camera2GroupBox.setTitle(_translate("FlowMonitoringWindow", "摄像头 2"))
        self.radioButton2_1.setText(_translate("FlowMonitoringWindow", "源 1"))
        self.radioButton2_2.setText(_translate("FlowMonitoringWindow", "源 2"))
        self.radioButton2_3.setText(_translate("FlowMonitoringWindow", "源 3"))
        self.camera3GroupBox.setTitle(_translate("FlowMonitoringWindow", "摄像头 3"))
        self.radioButton3_1.setText(_translate("FlowMonitoringWindow", "源 1"))
        self.radioButton3_2.setText(_translate("FlowMonitoringWindow", "源 2"))
        self.radioButton3_3.setText(_translate("FlowMonitoringWindow", "源 3"))
        self.flowData.setTitle(_translate("FlowMonitoringWindow", "人流量数据"))
        self.exportButton.setText(_translate("FlowMonitoringWindow", "导出数据"))
        self.label_people_flow_1.setText(_translate("FlowMonitoringWindow", "人流量：0"))
        self.label_people_flow_2.setText(_translate("FlowMonitoringWindow", "人流量：0"))
        self.label_people_flow_3.setText(_translate("FlowMonitoringWindow", "人流量：0"))
        self.peopleFlowToggle.setText(_translate("FlowMonitoringWindow", "启用人流量检测"))
